// Fragen-Sammlung für die Fragerunde.
// Jeder Eintrag: { text, category }
// Kategorien werden automatisch zu Filter-Chips auf /fragen.

window.QUESTIONS = [

  // ---------- Über dich (25) ----------
  { text: "Würdest du deine schönste Erinnerung hergeben, damit du deine schlimmste auslöschen kannst?", category: "Über dich" },
  { text: "Was würdest du an deinem Körper gerne verändern?", category: "Über dich" },
  { text: "Was versuchst du vor anderen Menschen zu verbergen?", category: "Über dich" },
  { text: "Was möchtest du gewesen sein?", category: "Über dich" },
  { text: "Wovor hast du am meisten Angst?", category: "Über dich" },
  { text: "Für welche Eigenschaften an dir hast du am öftesten Komplimente bekommen?", category: "Über dich" },
  { text: "Was denken andere über dich, das überhaupt nicht stimmt?", category: "Über dich" },
  { text: "Gibt es ein Gefühl, das du selten zulässt — und wovor hättest du Angst, wenn du es doch zuließest?", category: "Über dich" },
  { text: "Welche Rolle spielst du in Gruppen, ohne dass du sie bewusst gewählt hättest?", category: "Über dich" },
  { text: "Was an dir hat sich in den letzten fünf Jahren am meisten verändert?", category: "Über dich" },
  { text: "Worin bist du heimlich gut — etwas, das kaum jemand von dir weiß?", category: "Über dich" },
  { text: "Welchen Satz hast du dir selbst schon oft gesagt, aber noch nie wirklich geglaubt?", category: "Über dich" },
  { text: "Was bedeutet „zu Hause“ für dich — und wann hast du es zuletzt gespürt?", category: "Über dich" },
  { text: "Gibt es einen Teil von dir, den du erst in einer bestimmten Konstellation zeigst?", category: "Über dich" },
  { text: "Was tust du, wenn du dich unbeobachtet fühlst, was du nie jemandem erzählen würdest?", category: "Über dich" },
  { text: "Welcher deiner eigenen Sätze überrascht dich selbst immer wieder?", category: "Über dich" },
  { text: "Wann hast du zuletzt einen Moment gehabt, in dem du gedacht hast: „So bin ich wirklich“?", category: "Über dich" },
  { text: "Was an dir würdest du auf keinen Fall verändern?", category: "Über dich" },
  { text: "In welcher Situation bist du am meisten du selbst?", category: "Über dich" },
  { text: "Welchen Teil deiner Kindheit trägst du noch heute in dir?", category: "Über dich" },
  { text: "Vor welcher Wahrheit über dich selbst hast du am meisten Angst?", category: "Über dich" },
  { text: "Welches Kompliment hat dich nachhaltig geprägt?", category: "Über dich" },
  { text: "Worin unterscheidest du dich vom Rest deiner Familie?", category: "Über dich" },
  { text: "Was ist deine ehrliche Meinung zu dir selbst, wenn niemand zuhört?", category: "Über dich" },
  { text: "Worüber lachst du heimlich, obwohl du weißt, dass du es nicht solltest?", category: "Über dich" },

  // ---------- Werte & Richtung (25) ----------
  { text: "Glaubst du an Schicksal?", category: "Werte & Richtung" },
  { text: "Welche war die größte und bedeutendste Entscheidung, die du mal treffen musstest?", category: "Werte & Richtung" },
  { text: "Würdest du gerne wissen wollen wann du stirbst?", category: "Werte & Richtung" },
  { text: "Wenn du einem kleinen Kind einen Rat mitgeben könntest für den Rest seines Lebens — welcher wäre das?", category: "Werte & Richtung" },
  { text: "Gibst du dein Geld lieber für materielle Dinge oder für Erlebnisse aus?", category: "Werte & Richtung" },
  { text: "Was ist dein Lieblingszitat?", category: "Werte & Richtung" },
  { text: "Wärst du lieber weniger attraktiv und steinreich oder extrem gutaussehend, aber dafür arm?", category: "Werte & Richtung" },
  { text: "Wenn du nur noch einen Wert verteidigen dürftest — welcher wäre es?", category: "Werte & Richtung" },
  { text: "Was würdest du tun, wenn du wüsstest, du kannst nicht scheitern?", category: "Werte & Richtung" },
  { text: "Wann hast du zuletzt etwas getan, nur weil du es für richtig gehalten hast — nicht weil es klug war?", category: "Werte & Richtung" },
  { text: "Welche Regel, die du dir selbst gegeben hast, brichst du heimlich am häufigsten?", category: "Werte & Richtung" },
  { text: "Was hältst du für Luxus, was man nicht kaufen kann?", category: "Werte & Richtung" },
  { text: "Wofür würdest du alles stehen lassen und gehen?", category: "Werte & Richtung" },
  { text: "Welche Wahrheit kannst du nur schwer aussprechen, obwohl du weißt, sie wäre nötig?", category: "Werte & Richtung" },
  { text: "Was ist für dich der Unterschied zwischen „gut leben“ und „ehrlich leben“?", category: "Werte & Richtung" },
  { text: "Welchen Preis hast du für deine wichtigsten Entscheidungen bezahlt?", category: "Werte & Richtung" },
  { text: "Wenn du dein 20-jähriges Ich treffen könntest — welchen einen Satz würdest du sagen?", category: "Werte & Richtung" },
  { text: "Was ist für dich nicht verhandelbar?", category: "Werte & Richtung" },
  { text: "Wann hast du zuletzt bewusst die Kontrolle abgegeben — wie hat's sich angefühlt?", category: "Werte & Richtung" },
  { text: "Wofür hast du dich zuletzt geschämt — und warum eigentlich?", category: "Werte & Richtung" },
  { text: "Welche deiner Entscheidungen würdest du wieder genau so treffen, welche nicht?", category: "Werte & Richtung" },
  { text: "Was ist die wichtigste Lektion, die du aus einem Scheitern gelernt hast?", category: "Werte & Richtung" },
  { text: "Wann weißt du, dass etwas „genug“ ist?", category: "Werte & Richtung" },
  { text: "Was ist schwerer für dich: zu geben oder zu nehmen?", category: "Werte & Richtung" },
  { text: "Hat deine Definition von Erfolg sich verändert — wie?", category: "Werte & Richtung" },

  // ---------- Träume & Zukunft (15) ----------
  { text: "Welchen Beruf würdest du ausüben, wenn Geld keine Rolle spielen würde?", category: "Träume & Zukunft" },
  { text: "Welchen Traum wirst du dir, deiner Meinung nach, nie erfüllen können?", category: "Träume & Zukunft" },
  { text: "Was ist deine größte Fantasie?", category: "Träume & Zukunft" },
  { text: "Wie denkst du, sieht dein Leben in zehn Jahren aus?", category: "Träume & Zukunft" },
  { text: "Gibt es etwas, wovon du schon lange träumst, dich aber noch nicht getraut hast, es zu tun?", category: "Träume & Zukunft" },
  { text: "In fünf Jahren sitzt du wieder hier — was muss bis dahin passiert sein, damit du zufrieden bist?", category: "Träume & Zukunft" },
  { text: "Wenn du ein Buch schreiben würdest, wovon würde es handeln?", category: "Träume & Zukunft" },
  { text: "Welchen kleinen Luxus wünschst du dir im Alltag, erlaubst ihn dir aber nicht?", category: "Träume & Zukunft" },
  { text: "Wovon würdest du dir mehr wünschen, ohne dass es materiell wäre?", category: "Träume & Zukunft" },
  { text: "Welche Version deiner selbst möchtest du in 10 Jahren sehen?", category: "Träume & Zukunft" },
  { text: "Gibt es einen Traum, den du noch nie laut ausgesprochen hast?", category: "Träume & Zukunft" },
  { text: "Was hält dich davon ab, das zu machen, wovon du träumst?", category: "Träume & Zukunft" },
  { text: "Welche Reise willst du unbedingt noch machen — und was würde sie verändern?", category: "Träume & Zukunft" },
  { text: "Wenn du einen Tag lang eine andere Person sein könntest — wer wäre es?", category: "Träume & Zukunft" },
  { text: "Welchen Ort würdest du ungern sterben — welchen gern?", category: "Träume & Zukunft" },

  // ---------- Kindheit & Wurzeln (15) ----------
  { text: "Hattest du eine schöne Kindheit?", category: "Kindheit & Wurzeln" },
  { text: "Für welche Dinge hast du dich schon als Kind begeistert und hast dir diese Begeisterung bis heute beibehalten?", category: "Kindheit & Wurzeln" },
  { text: "Was war der größte Mist, den du als Jugendlicher gebaut hast?", category: "Kindheit & Wurzeln" },
  { text: "Welche Geschichte aus deiner Jugend wirst du deinen Kindern und Enkeln am häufigsten erzählen?", category: "Kindheit & Wurzeln" },
  { text: "Welcher Geruch bringt dich sofort in deine Kindheit zurück?", category: "Kindheit & Wurzeln" },
  { text: "Wer war dein bester Freund als Kind — und wisst ihr noch voneinander?", category: "Kindheit & Wurzeln" },
  { text: "Welche Geschichte wird in deiner Familie immer wieder erzählt?", category: "Kindheit & Wurzeln" },
  { text: "Was hättest du als Kind gebraucht, das du nicht bekommen hast?", category: "Kindheit & Wurzeln" },
  { text: "Welchen Beruf wolltest du werden, bevor du wusstest, was ein Beruf ist?", category: "Kindheit & Wurzeln" },
  { text: "Gibt es einen Ort aus deiner Kindheit, an den du nie mehr zurück möchtest?", category: "Kindheit & Wurzeln" },
  { text: "Was ist deine früheste Erinnerung?", category: "Kindheit & Wurzeln" },
  { text: "Welches Spielzeug hast du vermisst, als du älter wurdest?", category: "Kindheit & Wurzeln" },
  { text: "Wer in deiner Familie versteht dich am wenigsten — und wer am meisten?", category: "Kindheit & Wurzeln" },
  { text: "Was hat deine Eltern geprägt, das sich bei dir fortgesetzt hat?", category: "Kindheit & Wurzeln" },
  { text: "Worauf warst du als Kind besonders stolz?", category: "Kindheit & Wurzeln" },

  // ---------- Herzensmenschen (20) ----------
  { text: "Wer war für dich die einflussreichste Person in deinem Leben?", category: "Herzensmenschen" },
  { text: "Wann und mit welcher Person hattest du deinen größten Streit? Wie ist es ausgegangen?", category: "Herzensmenschen" },
  { text: "Welche aktuell lebende Person würdest du am liebsten treffen — und warum?", category: "Herzensmenschen" },
  { text: "Wenn du eine berühmte Persönlichkeit — egal ob lebendig oder tot — treffen dürftest: wer wäre es und warum?", category: "Herzensmenschen" },
  { text: "Was glaubst du haben wir gemeinsam?", category: "Herzensmenschen" },
  { text: "Wer in deinem Leben weiß etwas, das niemand anderes weiß?", category: "Herzensmenschen" },
  { text: "Wem schuldest du eine Entschuldigung, die du nie ausgesprochen hast?", category: "Herzensmenschen" },
  { text: "Wen vermisst du, ohne es zu sagen?", category: "Herzensmenschen" },
  { text: "Welche Freundschaft hat dich am meisten verändert?", category: "Herzensmenschen" },
  { text: "Wer hat dir zuletzt etwas gesagt, das du nicht vergessen konntest?", category: "Herzensmenschen" },
  { text: "Wem würdest du schreiben, wenn du wüsstest, du stirbst morgen?", category: "Herzensmenschen" },
  { text: "Welche Person in deinem Leben ist am schwersten zu erreichen — emotional?", category: "Herzensmenschen" },
  { text: "Wen hast du in deinem Leben unterschätzt?", category: "Herzensmenschen" },
  { text: "Welche Person hat dich am meisten liebgehabt — und weißt du, ob sie es wusste?", category: "Herzensmenschen" },
  { text: "Wer hat dir zum letzten Mal „Ich habe dich lieb“ gesagt?", category: "Herzensmenschen" },
  { text: "Mit welchem Menschen fühlst du dich ohne Worte verstanden?", category: "Herzensmenschen" },
  { text: "Wem gegenüber hast du dich am meisten verstellt — und warum?", category: "Herzensmenschen" },
  { text: "Welches Verhalten anderer trifft dich am härtesten?", category: "Herzensmenschen" },
  { text: "Wen beneidest du heimlich — und wofür?", category: "Herzensmenschen" },
  { text: "Mit wem würdest du gern noch einmal sprechen?", category: "Herzensmenschen" },
  { text: "Warst du schon mal emotional abhängig von einem Menschen?", category: "Herzensmenschen" },
  { text: "Hast du schon mal jemanden gebraucht — und gespürt, dass das ungesund war?", category: "Herzensmenschen" },
  { text: "Gibt es einen Menschen, ohne den du dir dein Leben damals nicht vorstellen konntest, und der heute nicht mehr da ist?", category: "Herzensmenschen" },
  { text: "Wann hast du zuletzt jemanden festgehalten, obwohl ein Teil von dir wusste, dass es nicht mehr trug?", category: "Herzensmenschen" },
  { text: "Hast du schon mal aus Angst vor dem Allein-Sein bei jemandem gewartet, der nicht zurückkam?", category: "Herzensmenschen" },
  { text: "Gibt es einen Menschen, dessen Stimmung deinen ganzen Tag färbt — und wann ist dir das zum ersten Mal aufgefallen?", category: "Herzensmenschen" },
  { text: "Was war die längste Zeit, in der du jemanden täglich vermisst hast — und wie hast du das ausgehalten?", category: "Herzensmenschen" },
  { text: "Wann hast du dich von einer emotionalen Abhängigkeit gelöst — und woran hast du gemerkt, dass es Zeit war?", category: "Herzensmenschen" },
  { text: "Wer hat dich zum ersten Mal so geliebt, dass du gemerkt hast, wie wenig du es vorher kanntest?", category: "Herzensmenschen" },
  { text: "Was war der erste Mensch, dessen Tod oder Verlust dir wirklich klar gemacht hat, dass Liebe und Zeit endlich sind?", category: "Herzensmenschen" },

  // ---------- Arbeit & Berufung (20) ----------
  { text: "Wann warst du zuletzt in deiner Arbeit so vertieft, dass du die Zeit vergessen hast — was hast du da gemacht?", category: "Arbeit & Berufung" },
  { text: "Welche Tätigkeit würdest du machen, auch wenn niemand dich dafür bezahlen würde?", category: "Arbeit & Berufung" },
  { text: "Wann hast du in deinem Job zuletzt einen echten Moment von Sinn gespürt — und wann das letzte Mal von Leere?", category: "Arbeit & Berufung" },
  { text: "Was frisst Energie in deiner Woche, ohne dass es einen klaren Output hat?", category: "Arbeit & Berufung" },
  { text: "Wenn dein heutiges Ich mit 22 wäre — würde es deinen jetzigen Job wählen?", category: "Arbeit & Berufung" },
  { text: "Welcher Beruf von Freund:innen oder Bekannten fasziniert dich heimlich?", category: "Arbeit & Berufung" },
  { text: "Was ist die ehrlichste Antwort auf die Frage „Warum machst du diesen Job?“ — jenseits von Geld?", category: "Arbeit & Berufung" },
  { text: "Wenn du in 20 Jahren auf dein Berufsleben zurückblickst — woran wirst du es messen?", category: "Arbeit & Berufung" },
  { text: "Was machst du heute, was dich in 10 Jahren wahrscheinlich nicht mehr ausfüllt?", category: "Arbeit & Berufung" },
  { text: "Wann warst du zuletzt in deiner Arbeit so vertieft, dass du die Zeit vergessen hast?", category: "Arbeit & Berufung" },
  { text: "Was würdest du tun, wenn Geld keine Rolle spielte — und was, wenn Status keine Rolle spielte?", category: "Arbeit & Berufung" },
  { text: "Was ist die ehrlichste Antwort auf die Frage „Warum machst du diesen Job?“?", category: "Arbeit & Berufung" },
  { text: "Wenn du in 20 Jahren zurückblickst — woran wirst du dein Berufsleben messen?", category: "Arbeit & Berufung" },
  { text: "Wofür arbeitest du eigentlich?", category: "Arbeit & Berufung" },
  { text: "Wann hast du zuletzt bei der Arbeit gedacht: „Dafür bin ich hier“?", category: "Arbeit & Berufung" },
  { text: "Welchen Teil deiner Arbeit hasst du — und warum machst du ihn trotzdem?", category: "Arbeit & Berufung" },
  { text: "Wie viel deines Selbstwerts hängt an dem, was du beruflich tust?", category: "Arbeit & Berufung" },
  { text: "Wenn du morgen gekündigt würdest — wäre es auch eine Erleichterung?", category: "Arbeit & Berufung" },
  { text: "Welches berufliche Kompliment war dir wirklich wichtig?", category: "Arbeit & Berufung" },
  { text: "Was würdest du deiner Arbeit in fünf Worten sagen?", category: "Arbeit & Berufung" },

  // ---------- Tiefgang (25) ----------
  { text: "Worüber denkst du abends manchmal nach, was du tagsüber verdrängst?", category: "Tiefgang" },
  { text: "Was würdest du sagen, wenn niemand zuhörte — und du wüsstest, dass es keine Folgen hat?", category: "Tiefgang" },
  { text: "Welche Frage hast du Angst, dir selbst zu stellen?", category: "Tiefgang" },
  { text: "Was ist eine Sorge, die du mit anderen nicht teilst — und warum nicht?", category: "Tiefgang" },
  { text: "Wovor hast du heimlich Angst, was die meisten Menschen wahrscheinlich nicht ahnen?", category: "Tiefgang" },
  { text: "Was wäre, wenn deine größte Angst tatsächlich einträte — wie würde dein Leben aussehen?", category: "Tiefgang" },
  { text: "Was hast du noch nie jemandem erzählt, was eigentlich Erzählens wert wäre?", category: "Tiefgang" },
  { text: "Welches Gefühl trägst du oft mit dir, ohne es zu benennen?", category: "Tiefgang" },
  { text: "Welche Beziehung in deinem Leben fühlt sich gerade nicht gut an, und du sprichst nicht darüber?", category: "Tiefgang" },
  { text: "Welcher Satz, den jemand mal zu dir gesagt hat, trägt dich noch heute?", category: "Tiefgang" },
  { text: "Welche Person würde es merken, wenn du plötzlich nicht mehr da wärst — und merkst du es bei ihr?", category: "Tiefgang" },
  { text: "Worüber denkst du abends nach, was du tagsüber verdrängst?", category: "Tiefgang" },
  { text: "Welche kleine tägliche Handlung hält dich stabil?", category: "Tiefgang" },
  { text: "Für welches Ereignis deines Lebens bist du am dankbarsten?", category: "Tiefgang" },
  { text: "Für welche drei Dinge in deinem Leben bist du am dankbarsten?", category: "Tiefgang" },
  { text: "Gibt es eine Erfahrung, die dein Leben nachhaltig verändert hat?", category: "Tiefgang" },
  { text: "Welches ist das beste Buch, das du gelesen hast?", category: "Tiefgang" },
  { text: "Wenn du ein Video haben könntest von einer Situation deiner Wahl aus deinem Leben — welche Situation wäre das?", category: "Tiefgang" },
  { text: "Was weißt du über dich, das du anderen nicht sagen könntest?", category: "Tiefgang" },
  { text: "Wann hast du zuletzt geweint — und was war der wirkliche Grund?", category: "Tiefgang" },
  { text: "Welche innere Stimme begleitet dich am meisten — und wie klingt sie?", category: "Tiefgang" },
  { text: "Was bereust du am meisten — und hast du dir selbst vergeben?", category: "Tiefgang" },
  { text: "Gibt es einen Moment, in dem du jemanden nicht losgelassen hast, obwohl er hätte gehen dürfen?", category: "Tiefgang" },
  { text: "Was würdest du sagen, wenn niemand antworten müsste?", category: "Tiefgang" },
  { text: "Was bedeutet Versöhnung für dich — mit dir selbst?", category: "Tiefgang" },

  // ---------- Leicht & Humor (22) ----------
  { text: "Welche historische Figur würde im Gruppenchat ständig auf „Nachricht gelesen“ machen — und warum gerade die?", category: "Leicht & Humor" },
  { text: "Bei einer Zombie-Apokalypse: Welches völlig unnütze Hobby würde dich überleben lassen?", category: "Leicht & Humor" },
  { text: "Welche zwei Promis würdest du zu einer Dinner-Party einladen, damit sie sich streiten?", category: "Leicht & Humor" },
  { text: "Würdest du lieber ein Jahr lang nur durch GIFs kommunizieren — oder jeden Satz mit einer Lüge beginnen?", category: "Leicht & Humor" },
  { text: "Dein Kühlschrank reproduziert mysteriös eine Zutat unbegrenzt — welche soll es sein und warum?", category: "Leicht & Humor" },
  { text: "Würdest du lieber wissen, wann du stirbst — oder wie?", category: "Leicht & Humor" },
  { text: "Welcher Film müsste neu verfilmt werden — aber als TikTok-Tanzchallenge?", category: "Leicht & Humor" },
  { text: "Welche Sportart sollte mit völlig falschen Regeln olympisch werden?", category: "Leicht & Humor" },
  { text: "Welcher Instagram-Filter beschreibt deine Persönlichkeit am besten — nicht dein Aussehen?", category: "Leicht & Humor" },
  { text: "Welche App sollte dringend eine „Das war Sarkasmus!“-Autokorrektur einführen?", category: "Leicht & Humor" },
  { text: "Welche völlig sinnlose Fähigkeit hast du in den letzten Jahren perfektioniert?", category: "Leicht & Humor" },
  { text: "Welcher Wikipedia-Artikel sollte gelöscht werden, um maximales Chaos zu verursachen?", category: "Leicht & Humor" },
  { text: "Welche historische Figur würde im Gruppenchat ständig auf „Nachricht gelesen“ machen?", category: "Leicht & Humor" },
  { text: "Du erbst ein Schloss — was machst du damit?", category: "Leicht & Humor" },
  { text: "Dein Kühlschrank reproduziert eine Zutat unbegrenzt — welche?", category: "Leicht & Humor" },
  { text: "Welcher Instagram-Filter beschreibt deine Persönlichkeit am besten?", category: "Leicht & Humor" },
  { text: "Welcher Film müsste als TikTok-Tanzchallenge neu verfilmt werden?", category: "Leicht & Humor" },
  { text: "Welche peinlichste Automatikreaktion passiert dir immer wieder?", category: "Leicht & Humor" },
  { text: "Welche Popsong-Zeile singst du in deinem Kopf, wenn niemand zuschaut?", category: "Leicht & Humor" },
  { text: "Welches Gericht würdest du essen, wenn Kalorien nicht zählen würden — eine Woche lang?", category: "Leicht & Humor" },
  { text: "Welche drei Alltagsentscheidungen brauchst du am längsten zu treffen?", category: "Leicht & Humor" },
  { text: "Welches Kleidungsstück aus deiner Jugend bereust du heute am meisten?", category: "Leicht & Humor" },

  // ---------- Absurd & Erlebt (12) ----------
  { text: "Was war das schlimmste Date, das du je hattest?", category: "Absurd & Erlebt" },
  { text: "Was ist das Peinlichste, das dir je beim Feiern passiert ist?", category: "Absurd & Erlebt" },
  { text: "Was ist das Lustigste, das du beim Feiern erlebt hast?", category: "Absurd & Erlebt" },
  { text: "Was war das größte Missverständnis, das dir je passiert ist?", category: "Absurd & Erlebt" },
  { text: "Was war das seltsamste Geschenk, das du je bekommen hast?", category: "Absurd & Erlebt" },
  { text: "Welche Prüfung oder welches Vorstellungsgespräch ist am schiefsten gelaufen?", category: "Absurd & Erlebt" },
  { text: "Was war das Unangenehmste, was du zufällig mitgehört hast?", category: "Absurd & Erlebt" },
  { text: "Gab es einen Moment, in dem du dachtest, du stirbst gleich?", category: "Absurd & Erlebt" },
  { text: "In welcher Situation warst du so fremd, dass es schon wieder lustig war?", category: "Absurd & Erlebt" },
  { text: "Welche Handwerker- oder Restaurant-Geschichte erzählst du am häufigsten?", category: "Absurd & Erlebt" },
  { text: "Was hat dich zuletzt so zum Lachen gebracht, dass du kurz Angst um deine Atmung hattest?", category: "Absurd & Erlebt" },
  { text: "Was war das Peinlichste, das dir in einer öffentlichen Situation passiert ist?", category: "Absurd & Erlebt" },

  // ---------- Bunt gemischt (38) ----------
  { text: "Was ist eine kleine Sache im Alltag, die dich unverhältnismäßig glücklich macht?", category: "Bunt gemischt" },
  { text: "Was hast du zuletzt zum allerersten Mal in deinem Leben gemacht?", category: "Bunt gemischt" },
  { text: "Welche kleine Sache lässt dich sofort nostalgisch werden?", category: "Bunt gemischt" },
  { text: "Gibt es etwas, das andere Leute oft an dir falsch einschätzen?", category: "Bunt gemischt" },
  { text: "Was hat dich zuletzt zum Staunen gebracht?", category: "Bunt gemischt" },
  { text: "Wenn dein Leben gerade ein Buch wäre — welchen Titel hätte es?", category: "Bunt gemischt" },
  { text: "Welches „unsichtbare Tattoo“ trägst du — also welche Erfahrung prägt dich, obwohl man es dir nicht ansieht?", category: "Bunt gemischt" },
  { text: "Angenommen, du könntest einen Tag mit deinem 15-jährigen Ich verbringen — was würdet ihr besprechen?", category: "Bunt gemischt" },
  { text: "In welcher Version deiner selbst fühlst du dich am wohlsten — und wann warst du zuletzt dort?", category: "Bunt gemischt" },
  { text: "Welche Eigenschaft an dir möchtest du unbedingt behalten, selbst wenn du mal 100 Jahre alt bist?", category: "Bunt gemischt" },
  { text: "Wen in deinem Leben würdest du gerne wieder anrufen, hast es aber zu lange nicht getan?", category: "Bunt gemischt" },
  { text: "Welche Eigenschaft deiner Eltern siehst du heute mit mehr Verständnis als früher?", category: "Bunt gemischt" },
  { text: "Was hast du jemandem zuletzt gesagt, was du schon länger hättest sagen sollen?", category: "Bunt gemischt" },
  { text: "Wem würdest du gerne noch einmal danken können — und wofür?", category: "Bunt gemischt" },
  { text: "Wenn du eine Sache an der Gesellschaft sofort ändern könntest — welche wäre das und warum?", category: "Bunt gemischt" },
  { text: "Welche Frage würdest du gerne mit „Ja“ beantworten können, kannst es aber (noch) nicht?", category: "Bunt gemischt" },
  { text: "Gibt es eine Erfahrung, die sich erst wie ein Misserfolg angefühlt hat, sich aber als wertvolle Lektion entpuppte?", category: "Bunt gemischt" },
  { text: "Welche kleine Entscheidung in deinem Leben hat überraschend große Auswirkungen gehabt?", category: "Bunt gemischt" },
  { text: "Welche Rolle spielst du unbewusst in Gruppen — und passt sie noch zu dir?", category: "Bunt gemischt" },
  { text: "Was nimmst du dir jedes Jahr vor, machst es aber nicht — und warum wahrscheinlich?", category: "Bunt gemischt" },
  { text: "Welcher Tag aus den letzten 12 Monaten war für dich besonders — und woran hast du das gemerkt?", category: "Bunt gemischt" },
  { text: "Wenn du wüsstest, dass dir genau ein Jahr bleibt — was würde sich sofort ändern, und was nicht?", category: "Bunt gemischt" },
  { text: "Was ist eine kleine tägliche Handlung, die dich stabil hält?", category: "Bunt gemischt" },
  { text: "Was würdest du gerne ausprobieren, hast dich aber bisher nie getraut?", category: "Bunt gemischt" },
  { text: "Angenommen, du hättest ab morgen ein Jahr frei von allen Verpflichtungen und genug Geld — wie würdest du es verbringen?", category: "Bunt gemischt" },
  { text: "Was ist deine „andere Karriere“ — das Leben, das du auch hättest führen können?", category: "Bunt gemischt" },
  { text: "Wenn dein Leben als Netflix-Serie erscheinen würde — welches Genre wäre es, und wie hieße die aktuelle Staffel?", category: "Bunt gemischt" },
  { text: "Welcher Satz, den jemand mal zu dir gesagt hat, ist geblieben?", category: "Bunt gemischt" },
  { text: "Welche kleine Geste von jemand anderem kann dich sofort für diese Person einnehmen?", category: "Bunt gemischt" },
  { text: "Welches „unsichtbare Tattoo“ trägst du — was prägt dich, obwohl man es dir nicht ansieht?", category: "Bunt gemischt" },
  { text: "Welche Erfahrung hat sich erst wie ein Misserfolg angefühlt — und war später eine wertvolle Lektion?", category: "Bunt gemischt" },
  { text: "Welche Person aus deinem Leben hat dich mehr geprägt, als sie selbst weiß?", category: "Bunt gemischt" },
  { text: "In welcher Beziehung spürst du gerade, dass Aufmerksamkeit fehlt?", category: "Bunt gemischt" },
  { text: "Wenn du wüsstest, dass dir genau ein Jahr bleibt — was würde sich sofort ändern, was nicht?", category: "Bunt gemischt" },
  { text: "Was würdest du gerne ausprobieren, hast dich aber nie getraut?", category: "Bunt gemischt" },
  { text: "Wenn du ein Jahr frei hättest und genug Geld — wie würdest du es verbringen?", category: "Bunt gemischt" },
  { text: "Angenommen, dein zukünftiges Ich schreibt dir einen Brief — was würde darin stehen?", category: "Bunt gemischt" },
  { text: "Was ist eine Sache, von der alle Leute begeistert scheinen und du kannst einfach nicht nachvollziehen wieso?", category: "Bunt gemischt" },

  // ---------- Ü18 · Spicy (22) ----------
  { text: "Was findest du sexy, was andere vielleicht nicht verstehen würden?", category: "Ü18 · Spicy" },
  { text: "Gibt es eine Fantasie, die du dich nie getraut hast auszusprechen?", category: "Ü18 · Spicy" },
  { text: "Welcher Moment mit einem Menschen war für dich der intimste — und warum?", category: "Ü18 · Spicy" },
  { text: "Welche Grenze hast du in Beziehungen neu verhandelt, weil sie nicht mehr gestimmt hat?", category: "Ü18 · Spicy" },
  { text: "Welches Tabu hast du heimlich spannend gefunden, ohne es laut auszusprechen?", category: "Ü18 · Spicy" },
  { text: "Was war der mutigste Moment in deinem Sexleben?", category: "Ü18 · Spicy" },
  { text: "Wann hast du dich zuletzt richtig begehrt gefühlt?", category: "Ü18 · Spicy" },
  { text: "Welches Thema rund um Sex fällt dir am schwersten anzusprechen?", category: "Ü18 · Spicy" },
  { text: "Welche Rolle spielt Sex in deinem Leben — verglichen mit vor fünf Jahren?", category: "Ü18 · Spicy" },
  { text: "Was macht dich im Bett unsicher?", category: "Ü18 · Spicy" },
  { text: "Gibt es etwas, wovon du weißt, dass es dich erregt, du dich aber scheust, es zuzugeben?", category: "Ü18 · Spicy" },
  { text: "Wie ehrlich bist du mit dir selbst in deinen erotischen Wünschen?", category: "Ü18 · Spicy" },
  { text: "Wann hattest du zuletzt richtig guten Sex — und was war anders als sonst?", category: "Ü18 · Spicy" },
  { text: "Welche Eigenschaft macht einen Menschen für dich sofort anziehend — jenseits vom Aussehen?", category: "Ü18 · Spicy" },
  { text: "Was war das Intimste, das du je jemandem geschrieben hast?", category: "Ü18 · Spicy" },
  { text: "Gibt es ein „Erstes Mal“, das noch kommen soll?", category: "Ü18 · Spicy" },
  { text: "Was fehlt dir in deinem Intimleben, ohne dass du es ansprichst?", category: "Ü18 · Spicy" },
  { text: "Welches Lied bringt dich sofort in eine bestimmte erotische Erinnerung zurück?", category: "Ü18 · Spicy" },
  { text: "Wie willst du gerade jetzt berührt werden?", category: "Ü18 · Spicy" },
  { text: "Was war das Riskanteste, was du je im Intimen getan hast?", category: "Ü18 · Spicy" },
  { text: "Wovon träumst du nachts, worüber du tagsüber nicht sprichst?", category: "Ü18 · Spicy" },
  { text: "Was wäre in deinem Intimleben heute möglich, wenn du weniger Scham hättest?", category: "Ü18 · Spicy" },
  { text: "Welcher Geruch eines Menschen wirkt auf dich sofort wie ein körperliches Angebot?", category: "Ü18 · Spicy" },
  { text: "Was würdest du jetzt gern ins Ohr geflüstert bekommen — kein Cliché, das echte?", category: "Ü18 · Spicy" },
  { text: "Welche Berührung, die niemand sonst kennt, holt dich sofort raus aus dem Kopf?", category: "Ü18 · Spicy" },
  { text: "Was war das Letzte, was du jemandem nicht zu sagen wagtest, weil es zu ehrlich-erregt war?", category: "Ü18 · Spicy" },
  { text: "Welches Kleidungsstück an einer anderen Person zieht dich magisch an, ohne dass du erklären könntest warum?", category: "Ü18 · Spicy" },
  { text: "Wenn du eine Szene schreiben dürftest, in der du dich gewünscht und gesehen fühlst — wo, wer, was passiert?", category: "Ü18 · Spicy" },
  { text: "Was machst du, was nur dir gefällt, das du nicht öffentlich teilen würdest — aber auch nicht ablegen willst?", category: "Ü18 · Spicy" },
  { text: "Welche Phase deines Lebens war die intensivste sexuell — und warum genau diese?", category: "Ü18 · Spicy" },
  { text: "Wie ist dein Verhältnis zu Spiegel und dir selbst — eher Abwender oder Beobachter?", category: "Ü18 · Spicy" },
  { text: "Welcher Moment aus deiner Vergangenheit holt sofort warmen Bauch zurück, wenn du dran denkst?", category: "Ü18 · Spicy" },
  { text: "Was würdest du gern einmal versuchen, das du dir bisher selbst nicht erlaubt hast?", category: "Ü18 · Spicy" },
  { text: "Welche Geste eines anderen ist nicht offensichtlich sexuell, wirkt auf dich aber eindeutig so?", category: "Ü18 · Spicy" },
  { text: "Wann hast du zuletzt jemanden bewusst angesehen und gewusst: ich will das, sage es aber nicht?", category: "Ü18 · Spicy" },
  { text: "Was möchtest du nach dem Sex hören — kein Liebesbekenntnis, einen ehrlichen Satz?", category: "Ü18 · Spicy" },
  { text: "Welche Phantasie kommt dir immer wieder, ohne dass du sie dir aussuchst?", category: "Ü18 · Spicy" },
  { text: "Wie ist dein Verhältnis zu deinem eigenen Körper gerade — fremd, vertraut, neugierig, bewusst?", category: "Ü18 · Spicy" },
  { text: "Welche Art zu küssen lässt dich sofort wissen, ob jemand zu dir passt?", category: "Ü18 · Spicy" },
  { text: "Welcher Satz im Bett wirkt auf dich, weil er nicht klingt wie eine Floskel?", category: "Ü18 · Spicy" },
  { text: "Welche Tageszeit ist deine ehrlichste sexuelle Tageszeit — und warum?", category: "Ü18 · Spicy" },
  { text: "Welches Wort, das du sonst nie verwendest, würdest du jetzt jemandem sagen wollen?", category: "Ü18 · Spicy" },
  { text: "Was kannst du im Bett, was du außerhalb nicht kannst?", category: "Ü18 · Spicy" },
  { text: "Welche Form von Kontrolle abzugeben fällt dir am schwersten — und welche wäre eine Erleichterung?", category: "Ü18 · Spicy" },
  { text: "Welcher Moment körperlicher Nähe — nicht Sex — hat dich zuletzt überrascht oder berührt?", category: "Ü18 · Spicy" },
  { text: "Was vermisst du an deinem Körper aus deinen Zwanzigern — und was schätzt du an deinem heutigen?", category: "Ü18 · Spicy" },
  { text: "Wo wirst du gerade ungern angefasst — und wo unbedingt?", category: "Ü18 · Spicy" },

  // ---------- Schräg & Ehrlich (15) ----------
  { text: "Was war die letzte Lüge, die du jemandem erzählt hast — auch eine kleine?", category: "Schräg & Ehrlich" },
  { text: "Wann hast du zuletzt heimlich die Story von jemandem angeschaut, der dich gerade beschäftigt?", category: "Schräg & Ehrlich" },
  { text: "Was würde in deinem Browser-Verlauf der letzten Woche stehen, das du niemandem zeigen würdest?", category: "Schräg & Ehrlich" },
  { text: "Welche Person aus deinem Umfeld hast du in den letzten Tagen heimlich für ihr Leben beneidet — und welchen Aspekt genau?", category: "Schräg & Ehrlich" },
  { text: "Wann hast du zuletzt eine Nachricht zehnmal umformuliert, bevor du sie abgeschickt hast?", category: "Schräg & Ehrlich" },
  { text: "Wie oft denkst du an deinen Ex — ehrlich, nicht die Antwort, die du sonst gibst?", category: "Schräg & Ehrlich" },
  { text: "Was sagst du, wenn jemand fragt wie's geht — und was wäre die ehrliche Antwort heute?", category: "Schräg & Ehrlich" },
  { text: "Welche Eigenschaft bei deinen engsten Freund:innen nervt dich richtig, sagst aber nichts?", category: "Schräg & Ehrlich" },
  { text: "Welcher Mensch fehlt dir, mit dem du seit Monaten nicht geschrieben hast — und warum schreibst du eigentlich nicht?", category: "Schräg & Ehrlich" },
  { text: "Welches Lied hörst du heimlich auf Repeat, das absolut nicht zu deinem Image passt?", category: "Schräg & Ehrlich" },
  { text: "Wann hast du zuletzt so getan, als kennst du etwas, das du gar nicht kennst — ein Buch, einen Film, ein Wort?", category: "Schräg & Ehrlich" },
  { text: "Was ist das Banalste, worüber du dich in den letzten Tagen ernsthaft aufgeregt hast?", category: "Schräg & Ehrlich" },
  { text: "Welche Beleidigung oder kritische Bemerkung gegen dich beschäftigt dich noch Monate später, obwohl sie längst vergessen sein müsste?", category: "Schräg & Ehrlich" },
  { text: "Welche Person würdest du am liebsten heimlich für einen Tag werden — und warum genau die?", category: "Schräg & Ehrlich" },
  { text: "Welcher Mensch in deinem Leben kennt eine Version von dir, die alle anderen nicht kennen — und was ist anders an dieser Version?", category: "Schräg & Ehrlich" },

  // ---------- Banal & Tief (15) ----------
  { text: "Welche Geste deiner Eltern machst du nach, ohne dass du es merkst?", category: "Banal & Tief" },
  { text: "Welcher Geruch reißt dich sofort in eine konkrete Erinnerung — und welche?", category: "Banal & Tief" },
  { text: "Welche kleine Routine zwischen dir und einem geliebten Menschen ist so unscheinbar, dass sie kaum benennbar ist — und trägt trotzdem alles?", category: "Banal & Tief" },
  { text: "Welcher Satz, den jemand dir mal gesagt hat, läuft seitdem wie eine Hintergrundmelodie in dir?", category: "Banal & Tief" },
  { text: "Was hast du als Kind gefühlt, das du heute nicht mehr fühlst — und vermisst?", category: "Banal & Tief" },
  { text: "Welcher Ort, an dem du nur kurz warst, taucht in deinem Kopf immer wieder auf?", category: "Banal & Tief" },
  { text: "Welcher Lieblingssatz deiner Mutter oder deines Vaters taucht in dir auf, wenn dir etwas wehtut?", category: "Banal & Tief" },
  { text: "Wann hast du zuletzt etwas Schönes gesehen und niemandem davon erzählt — und warum nicht?", category: "Banal & Tief" },
  { text: "Welcher Gegenstand in deiner Wohnung hat dich am längsten begleitet — und warum hast du ihn nie weggeworfen?", category: "Banal & Tief" },
  { text: "Welcher Witz deines Vaters oder deiner Mutter geistert noch in dir, obwohl er gar nicht so witzig war?", category: "Banal & Tief" },
  { text: "Wann hast du zuletzt geweint, ohne genau zu wissen warum?", category: "Banal & Tief" },
  { text: "Welche kleine Erinnerung an jemanden, der nicht mehr in deinem Leben ist, kannst du immer wieder abrufen?", category: "Banal & Tief" },
  { text: "An welchem Tag im Jahr ist deine Stimmung jedes Jahr seltsam ähnlich — und welcher Tag ist das?", category: "Banal & Tief" },
  { text: "Welche gewöhnliche Situation aus deinem Leben würdest du als Foto rahmen, wenn du ehrlich antwortest?", category: "Banal & Tief" },
  { text: "Welchen Moment hast du heute oder gestern bewusst zu schnell beendet — und was hätte passieren können, wenn du geblieben wärst?", category: "Banal & Tief" },

  // ---------- 100 Date-Fragen (100) ----------
  // Strukturiert nach psychologischer Eskalation (angelehnt an Aron, Perel, Big Five, Bindungstheorie, Love Languages).
  // 7 Phasen: Tasten (1-15) · Alltag (16-30) · Werte (31-45) · Liebe (46-60) · Wurzeln (61-72) · Schatten (73-85) · Zukunft & Tiefe (86-100)
  // Wer alle 100 durchgeht, hat ein präzises psychologisches Profil und einen langen, lustigen Abend.

  // — Phase 1 · Erstes Tasten (1-15) — leichte Eisbrecher
  { text: "Was war dein erster Eindruck von mir — vor zwei Minuten, jetzt?", category: "100 Kennenlern-Fragen" },
  { text: "Wenn du in drei Worten sagen müsstest, wie du heute hier ankommst — welche drei?", category: "100 Kennenlern-Fragen" },
  { text: "Was war heute Morgen dein erster Gedanke?", category: "100 Kennenlern-Fragen" },
  { text: "Wenn ich dein heutiges Outfit deuten würde — welche Botschaft schickst du damit?", category: "100 Kennenlern-Fragen" },
  { text: "Welches Lied lief heute in deinem Kopf, während du hierher gekommen bist?", category: "100 Kennenlern-Fragen" },
  { text: "Was würdest du essen, wenn du heute Abend keine Manieren bräuchtest?", category: "100 Kennenlern-Fragen" },
  { text: "Welches absolut nutzlose Talent hast du, das fast niemand kennt?", category: "100 Kennenlern-Fragen" },
  { text: "Bist du eher Frühaufsteherin oder Nachteule — und seit wann eigentlich?", category: "100 Kennenlern-Fragen" },
  { text: "Was war die letzte Sache, über die du wirklich laut gelacht hast?", category: "100 Kennenlern-Fragen" },
  { text: "Auf welcher Skala von eins bis zehn bist du gerade nervös — ehrlich?", category: "100 Kennenlern-Fragen" },
  { text: "Was war die schlimmste Mode-Phase deines Lebens?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Eigenheit von dir merken Menschen meistens erst nach dem zweiten Treffen?", category: "100 Kennenlern-Fragen" },
  { text: "Was hast du heimlich auf dem Handy gespeichert, das du keinem zeigen würdest?", category: "100 Kennenlern-Fragen" },
  { text: "Wenn du eine fiktive Figur wärst — welche, und warum genau die?", category: "100 Kennenlern-Fragen" },
  { text: "Was war der peinlichste Moment der letzten Woche?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Marotte von dir würde dich in einer Netflix-Doku berühmt machen?", category: "100 Kennenlern-Fragen" },
  { text: "Welcher Spitzname aus deiner Schulzeit passt heute eigentlich noch — auch wenn du ihn nie zugeben würdest?", category: "100 Kennenlern-Fragen" },

  // — Phase 2 · Alltag & Geschmack — Big-Five-light: Wie tickst du?
  { text: "Wie sieht ein perfekter Sonntag bei dir aus — Stunde für Stunde?", category: "100 Kennenlern-Fragen" },
  { text: "Wenn du zwei Tage komplett für dich hättest, ohne Verpflichtung — was würdest du tun?", category: "100 Kennenlern-Fragen" },
  { text: "Bist du eher Plan-Mensch oder Spontan-Mensch?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Routine deines Tages willst du nicht missen?", category: "100 Kennenlern-Fragen" },
  { text: "Was ist eine Eigenschaft, die andere an dir gut finden, die du selbst aber nervig findest?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Bücher, Filme oder Serien haben dich wirklich verändert?", category: "100 Kennenlern-Fragen" },
  { text: "Was machst du, wenn du gestresst bist — wirklich, nicht das, was gut klingt?", category: "100 Kennenlern-Fragen" },
  { text: "Magst du Menschen lieber in großen Runden oder in kleinen Tiefen-Gesprächen?", category: "100 Kennenlern-Fragen" },
  { text: "Wann hast du zuletzt etwas getan, was dich aus deiner Komfortzone gebracht hat?", category: "100 Kennenlern-Fragen" },
  { text: "Wo wärst du jetzt am liebsten auf der Welt — wenn Geld und Zeit egal wären?", category: "100 Kennenlern-Fragen" },
  { text: "Was ist dein verstecktes Hobby, das du nicht im Smalltalk erzählst?", category: "100 Kennenlern-Fragen" },
  { text: "Wann fühlst du dich richtig lebendig?", category: "100 Kennenlern-Fragen" },
  { text: "Wann fühlst du dich seltsam fern von dir selbst?", category: "100 Kennenlern-Fragen" },
  { text: "Welches Essen würdest du jeden Tag essen können?", category: "100 Kennenlern-Fragen" },
  { text: "Was wäre dein perfektes Frühstück mit jemandem, den du gut kennst?", category: "100 Kennenlern-Fragen" },
  { text: "Wenn du eine Werbung drehen müsstest, in der nur DU vorkommst — was bewirbst du am ehrlichsten?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Sache machst du heimlich richtig gut, gibst aber nicht damit an?", category: "100 Kennenlern-Fragen" },

  // — Phase 3 · Werte & Haltung — was wirklich zählt
  { text: "Was ist dir im Leben gerade am wichtigsten?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Werte hast du von zuhause mitbekommen, die du dankbar trägst?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Werte deiner Eltern hast du bewusst abgelehnt?", category: "100 Kennenlern-Fragen" },
  { text: "Was empört dich gerade an der Welt — und was lässt dich hoffen?", category: "100 Kennenlern-Fragen" },
  { text: "Wofür bist du gerade ganz konkret dankbar?", category: "100 Kennenlern-Fragen" },
  { text: "Wo ziehst du klare Grenzen — und wo bist du erstaunlich tolerant?", category: "100 Kennenlern-Fragen" },
  { text: "Was ist eine Überzeugung, die du vor fünf Jahren hattest und heute nicht mehr?", category: "100 Kennenlern-Fragen" },
  { text: "Was ist deine unpopulärste Meinung, die du wirklich vertrittst?", category: "100 Kennenlern-Fragen" },
  { text: "Worüber kannst du nicht witzeln, egal wie locker der Moment ist?", category: "100 Kennenlern-Fragen" },
  { text: "Wem oder was vertraust du blind — und wem oder was nie?", category: "100 Kennenlern-Fragen" },
  { text: "Was ist Erfolg für dich — heute, nicht damals?", category: "100 Kennenlern-Fragen" },
  { text: "Was würdest du mit zehntausend Euro tun, die nur diese Woche verfügbar sind?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Eigenschaft ist für dich Dealbreaker bei Menschen, mit denen du Zeit verbringst?", category: "100 Kennenlern-Fragen" },
  { text: "Wann hast du das letzte Mal etwas geglaubt, das sich später als falsch herausstellte?", category: "100 Kennenlern-Fragen" },
  { text: "Was hältst du für die größte Lüge unserer Zeit?", category: "100 Kennenlern-Fragen" },
  { text: "Wofür würdest du im Internet einen Streit anfangen — und was war zuletzt der Anlass?", category: "100 Kennenlern-Fragen" },
  { text: "Wenn du eine Sekte gründen müsstest — was wäre die Pflichtkleidung?", category: "100 Kennenlern-Fragen" },

  // — Phase 4 · Beziehungen & Liebe — Bindungsstil, Liebessprachen, Beziehungs-DNA
  { text: "Wie zeigst du jemandem, dass du sie oder ihn magst — ohne es zu sagen?", category: "100 Kennenlern-Fragen" },
  { text: "Wie willst du selbst geliebt werden — Worte, Berührung, Zeit, Geschenke, Taten?", category: "100 Kennenlern-Fragen" },
  { text: "Was hast du in deiner letzten Beziehung über dich gelernt?", category: "100 Kennenlern-Fragen" },
  { text: "Was war das Schönste, das jemand für dich getan hat — leise und ohne Show?", category: "100 Kennenlern-Fragen" },
  { text: "Was war die Beziehung, die dich am meisten geprägt hat — und wie?", category: "100 Kennenlern-Fragen" },
  { text: "Bist du eher die Person, die zuerst schreibt, oder die Person, die wartet?", category: "100 Kennenlern-Fragen" },
  { text: "Wie reagierst du, wenn jemand dich enttäuscht?", category: "100 Kennenlern-Fragen" },
  { text: "Was bedeutet Treue für dich — die unsexy ehrliche Antwort?", category: "100 Kennenlern-Fragen" },
  { text: "Wie fühlt sich für dich gute Nähe an — und ab wann wird sie zu viel?", category: "100 Kennenlern-Fragen" },
  { text: "Was machst du, wenn du verletzt bist — sprichst du, ziehst du dich zurück, eskalierst du?", category: "100 Kennenlern-Fragen" },
  { text: "Welche kleine Geste in einer Beziehung würde dir niemals langweilig?", category: "100 Kennenlern-Fragen" },
  { text: "Wann hast du dich zuletzt richtig verliebt gefühlt — wann immer das war?", category: "100 Kennenlern-Fragen" },
  { text: "Was war die ehrlichste Sache, die jemand jemals zu dir gesagt hat?", category: "100 Kennenlern-Fragen" },
  { text: "Wie sieht für dich ein perfekter gemeinsamer Abend in fünf Jahren aus?", category: "100 Kennenlern-Fragen" },
  { text: "Was an dir wird in einer guten Beziehung sichtbar, das sonst keiner sieht?", category: "100 Kennenlern-Fragen" },
  { text: "Welche „rote Flagge" bei anderen ist eigentlich heimlich dein Typ?", category: "100 Kennenlern-Fragen" },

  // — Phase 5 · Wurzeln & Familie — woher du kommst, was du mitschleppst
  { text: "Wer in deiner Familie hat dich am stärksten geprägt — und wie?", category: "100 Kennenlern-Fragen" },
  { text: "Was war die wichtigste Lektion, die du als Kind gelernt hast — gut oder schlecht?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Geste deiner Eltern machst du, ohne es zu merken?", category: "100 Kennenlern-Fragen" },
  { text: "Wie war deine Beziehung zu deiner Mutter mit fünfzehn — wie ist sie heute?", category: "100 Kennenlern-Fragen" },
  { text: "Wie war deine Beziehung zu deinem Vater mit fünfzehn — wie ist sie heute?", category: "100 Kennenlern-Fragen" },
  { text: "Welcher Satz aus deiner Kindheit läuft heute noch in deinem Kopf?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Familientradition behältst du, welche lässt du sterben?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Konflikte kennst du aus deiner Familie, die du in eigene Beziehungen mitbringst?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Eigenschaft eines Geschwisters, einer Cousine, eines Freundes wünschst du dir manchmal selbst?", category: "100 Kennenlern-Fragen" },
  { text: "Wie wurde in deiner Familie über Geld gesprochen — und wie heute zwischen dir und Geld?", category: "100 Kennenlern-Fragen" },
  { text: "Wie wurde in deiner Familie über Liebe gesprochen — wenn überhaupt?", category: "100 Kennenlern-Fragen" },
  { text: "Was würdest du anders machen, wenn du selbst eines Tages Kinder hast?", category: "100 Kennenlern-Fragen" },
  { text: "Welcher Familien-Spruch deiner Eltern ist absurd — und trotzdem irgendwie wahr?", category: "100 Kennenlern-Fragen" },

  // — Phase 6 · Schatten & Verletzlichkeit — was selten ausgesprochen wird
  { text: "Wovor hast du gerade am meisten Angst, wenn du ehrlich bist?", category: "100 Kennenlern-Fragen" },
  { text: "Was an dir hast du am längsten zu verstecken versucht?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Eigenschaft an dir wünschst du dir, du hättest sie nicht?", category: "100 Kennenlern-Fragen" },
  { text: "In welchem Bereich deines Lebens fühlst du dich gerade gerade so durchhängend?", category: "100 Kennenlern-Fragen" },
  { text: "Wann hast du zuletzt etwas Falsches getan und niemandem davon erzählt?", category: "100 Kennenlern-Fragen" },
  { text: "Was für eine Sache wäre, wenn jemand sie über dich wüsste, gerade noch okay — und welche eine Stufe drüber wäre nicht okay?", category: "100 Kennenlern-Fragen" },
  { text: "Was bereust du wirklich — keine Pose, sondern den realen Stachel?", category: "100 Kennenlern-Fragen" },
  { text: "Wann warst du das letzte Mal so richtig einsam, obwohl Menschen um dich waren?", category: "100 Kennenlern-Fragen" },
  { text: "Welcher Mensch fehlt dir gerade — und warum schreibst du nicht?", category: "100 Kennenlern-Fragen" },
  { text: "Worüber hast du dich zuletzt heimlich geschämt?", category: "100 Kennenlern-Fragen" },
  { text: "Was sagst du anderen, was du selbst gerade noch nicht glauben kannst?", category: "100 Kennenlern-Fragen" },
  { text: "Welcher Teil deiner Vergangenheit ist noch nicht ganz vorbei?", category: "100 Kennenlern-Fragen" },
  { text: "Wenn du heute weinen würdest — worüber wäre es?", category: "100 Kennenlern-Fragen" },

  // — Phase 7 · Zukunft, Sex, Konflikt & Schluss (86-100) — die ehrlichsten Schlussfragen
  { text: "Wie sieht dein Leben in fünf Jahren aus — die Vision, an die du wirklich glaubst?", category: "100 Kennenlern-Fragen" },
  { text: "Welcher unrealisierte Traum drückt dich am meisten?", category: "100 Kennenlern-Fragen" },
  { text: "Welche Rolle spielt Sex in deinem Leben — verglichen mit anderen Bereichen?", category: "100 Kennenlern-Fragen" },
  { text: "Was ist dir körperliche Nähe heute wert?", category: "100 Kennenlern-Fragen" },
  { text: "Wie streitest du — laut, leise, intellektuell, in Tränen, im Schweigen?", category: "100 Kennenlern-Fragen" },
  { text: "Was sind die drei Dinge, an denen jede deiner Beziehungen am Ende gescheitert ist?", category: "100 Kennenlern-Fragen" },
  { text: "Was möchtest du in einer Beziehung das nächste Mal anders machen?", category: "100 Kennenlern-Fragen" },
  { text: "Was muss eine Person mitbringen, damit du dich richtig fallen lassen kannst?", category: "100 Kennenlern-Fragen" },
  { text: "Was würde es brauchen, dass du in fünf Jahren zurückschaust und sagst: das war ein gutes Jahrfünft?", category: "100 Kennenlern-Fragen" },
  { text: "Wenn du wüsstest, dass du in genau einem Jahr stirbst — was würdest du sofort ändern?", category: "100 Kennenlern-Fragen" },
  { text: "Was ist eine Sache, die du jetzt sagen müsstest, damit du nicht in zehn Jahren bedauerst, sie nie gesagt zu haben?", category: "100 Kennenlern-Fragen" },
  { text: "Was hat sich an dir in diesem Gespräch gerade verändert — auch nur ein Hauch?", category: "100 Kennenlern-Fragen" },
  { text: "Was ist eine Frage, die du mich jetzt fragen wolltest, dich aber nicht getraut hast?", category: "100 Kennenlern-Fragen" },
  { text: "Was vermutest du gerade über mich, das ich dir vermutlich nicht erzählt habe?", category: "100 Kennenlern-Fragen" },
  { text: "Wie wirst du dich in drei Tagen an diesen Abend erinnern?", category: "100 Kennenlern-Fragen" },

  // ---------- Match-Eisbrecher (30) ----------
  // Originelle Eröffnungs-Fragen für Tinder, Bumble, Hinge & Co — kurz, mit
  // Augenzwinkern, einladend zur Antwort. Vermeiden „Hey, wie geht's"-Sumpf,
  // wirken auch bei Frauen, weil sie nicht plump sondern spielerisch sind.
  { text: "Wir sitzen am Flughafen, vier Stunden Verspätung, Bar ist offen — was ist dein Plan?", category: "Match-Eisbrecher" },
  { text: "Wenn ich dich auf einen Roman reduzieren müsste — Genre und Untertitel?", category: "Match-Eisbrecher" },
  { text: "Drei Wörter, die mich davon überzeugen, dich zu treffen — los.", category: "Match-Eisbrecher" },
  { text: "Was war heute der schrägste Opener, den du auf einer Dating-App bekommen hast?", category: "Match-Eisbrecher" },
  { text: "Stell dir vor, wir machen das erste Date schon morgen — was schlägst du vor, das nicht „einen Kaffee trinken" ist?", category: "Match-Eisbrecher" },
  { text: "Auf einer Skala von „Bibliothek-Tee-Date" bis „spontan nach Berlin" — wo bist du heute?", category: "Match-Eisbrecher" },
  { text: "Wenn wir uns vor zehn Jahren getroffen hätten — was wäre da schiefgelaufen?", category: "Match-Eisbrecher" },
  { text: "Ich brauche genau eine Frage, die du dich nie zu fragen traust. Lass hören.", category: "Match-Eisbrecher" },
  { text: "Du bist Drehbuch-Autorin von einem Film über uns. Wie lautet die erste Szene?", category: "Match-Eisbrecher" },
  { text: "Wenn dein Profil ein Warnschild bräuchte — was steht drauf?", category: "Match-Eisbrecher" },
  { text: "Welche Schwäche hast du, mit der du dich heimlich gut findest?", category: "Match-Eisbrecher" },
  { text: "Ich tippe drei Vermutungen über dich, du sagst „ja, nein, fast" — bereit?", category: "Match-Eisbrecher" },
  { text: "Wenn wir hier matchen, aber nie schreiben — was würdest du dir später wünschen, hättest du gefragt?", category: "Match-Eisbrecher" },
  { text: "Was war dein kleines Glück heute, das du noch keinem erzählt hast?", category: "Match-Eisbrecher" },
  { text: "Erkläre mir kurz dein Lieblings-Hobby so, als wäre ich misstrauisch.", category: "Match-Eisbrecher" },
  { text: "Wenn du jetzt aus dem Fenster schaust — was siehst du, das du sonst nicht beachtest?", category: "Match-Eisbrecher" },
  { text: "Welcher Song läuft, wenn du dich auf was Schönes freust?", category: "Match-Eisbrecher" },
  { text: "Was ist dein Sonntags-Ritual, das niemand kennt?", category: "Match-Eisbrecher" },
  { text: "Wenn ich dich um drei Uhr nachts mit einer Frage wecken dürfte — welche wäre okay?", category: "Match-Eisbrecher" },
  { text: "Was hast du heute auf Spotify gehört, das du leise weiterhörst, wenn jemand reinkommt?", category: "Match-Eisbrecher" },
  { text: "Du darfst genau einmal lügen über dich. Welche Lüge wäre lustig?", category: "Match-Eisbrecher" },
  { text: "Welche Eigenschaft an dir würden deine engsten Freund:innen sofort als dein Markenzeichen nennen?", category: "Match-Eisbrecher" },
  { text: "Wenn unsere erste Nachricht der Anfang eines Buchs wäre — wer schreibt's, du oder ich?", category: "Match-Eisbrecher" },
  { text: "Was ist die schönste Sache, die jemand mal über dich gesagt hat?", category: "Match-Eisbrecher" },
  { text: "Ich gebe dir drei Optionen für unser erstes Treffen — Spaziergang, Bar, Galerie. Du gibst mir eine vierte, die ich nicht erwartet hätte.", category: "Match-Eisbrecher" },
  { text: "Was machst du, wenn du dich richtig wohl fühlst — etwas, das nur du machst?", category: "Match-Eisbrecher" },
  { text: "Wenn du heute Abend einen Brief an dein 16-jähriges Ich schreiben dürftest — was wäre der erste Satz?", category: "Match-Eisbrecher" },
  { text: "Welcher Ort in deiner Stadt fühlt sich an wie nur deiner?", category: "Match-Eisbrecher" },
  { text: "Was war das letzte Buch, der letzte Film oder die letzte Folge, die dich richtig getroffen hat?", category: "Match-Eisbrecher" },
  { text: "Wenn ich rate, was du gleich antworten wirst, und es trifft zu — was hätte ich gewonnen?", category: "Match-Eisbrecher" },

];

window.QUESTION_CATEGORIES = [...new Set(window.QUESTIONS.map(q => q.category))];
